### ISSUE TITLE
Is it possible to remove IO from the Di's logging function?

### ISSUE THREAD

**Issue by k0001** [k0001/di#11]
cc @shlevy

**Comment by shlevy** [comment]
The idea would be to make `Di` either a pure data structure or, if needed for efficiency, an associated datatype of the `MonadDi` class, and have `log :: Di path msg -> Level -> msg -> m ()` be part of that class (and similar for `log'` but possibly in a different class).

**Comment by k0001** [comment]
I'm closing this in favor of #1 

In general: We need `IO` for the goals `di` targets, so doing this is not really possible.
