### ISSUE TITLE
Consider making Level parametrizable

### ISSUE THREAD

**Issue by k0001** [k0001/di#5]
Four levels of logging might no be enough for some cases, we might want to make this personalizable. It's not clear to me whether this is truly necessary though, in light of the current levels and #4

**Comment by shlevy** [comment]
Well take e.g. nix's internal logging, which has 6 levels https://github.com/NixOS/nix/blob/0a97eb6bd7d459de80432a5dbf39daf16647bb8c/src/libutil/logging.hh#L7-L14

**Comment by k0001** [comment]
Done!
